/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConstructionFeedsRouteImport } from './routes/api/construction-feeds'
import { Route as ApiDodgeProjectsRouteImport } from './routes/api/dodge/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConstructionFeedsRoute = ApiConstructionFeedsRouteImport.update({
  id: '/api/construction-feeds',
  path: '/api/construction-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDodgeProjectsRoute = ApiDodgeProjectsRouteImport.update({
  id: '/api/dodge/projects',
  path: '/api/dodge/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/construction-feeds' | '/api/dodge/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/construction-feeds' | '/api/dodge/projects'
  id: '__root__' | '/' | '/api/construction-feeds' | '/api/dodge/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConstructionFeedsRoute: typeof ApiConstructionFeedsRoute
  ApiDodgeProjectsRoute: typeof ApiDodgeProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/construction-feeds': {
      id: '/api/construction-feeds'
      path: '/api/construction-feeds'
      fullPath: '/api/construction-feeds'
      preLoaderRoute: typeof ApiConstructionFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dodge/projects': {
      id: '/api/dodge/projects'
      path: '/api/dodge/projects'
      fullPath: '/api/dodge/projects'
      preLoaderRoute: typeof ApiDodgeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConstructionFeedsRoute: ApiConstructionFeedsRoute,
  ApiDodgeProjectsRoute: ApiDodgeProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
