/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MbmaRouteImport } from './routes/mbma'
import { Route as TargetAttackRouteImport } from './routes/target-attack'
import { Route as ApiConstructionFeedsRouteImport } from './routes/api/construction-feeds'
import { Route as ApiMarketNewsRouteImport } from './routes/api/market-news'
import { Route as ApiDodgeProjectsRouteImport } from './routes/api/dodge/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MbmaRoute = MbmaRouteImport.update({
  id: '/mbma',
  path: '/mbma',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetAttackRoute = TargetAttackRouteImport.update({
  id: '/target-attack',
  path: '/target-attack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConstructionFeedsRoute = ApiConstructionFeedsRouteImport.update({
  id: '/api/construction-feeds',
  path: '/api/construction-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketNewsRoute = ApiMarketNewsRouteImport.update({
  id: '/api/market-news',
  path: '/api/market-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDodgeProjectsRoute = ApiDodgeProjectsRouteImport.update({
  id: '/api/dodge/projects',
  path: '/api/dodge/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mbma': typeof MbmaRoute
  '/target-attack': typeof TargetAttackRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mbma': typeof MbmaRoute
  '/target-attack': typeof TargetAttackRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mbma': typeof MbmaRoute
  '/target-attack': typeof TargetAttackRoute
  '/api/construction-feeds': typeof ApiConstructionFeedsRoute
  '/api/market-news': typeof ApiMarketNewsRoute
  '/api/dodge/projects': typeof ApiDodgeProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mbma'
    | '/target-attack'
    | '/api/construction-feeds'
    | '/api/market-news'
    | '/api/dodge/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mbma'
    | '/target-attack'
    | '/api/construction-feeds'
    | '/api/market-news'
    | '/api/dodge/projects'
  id:
    | '__root__'
    | '/'
    | '/mbma'
    | '/target-attack'
    | '/api/construction-feeds'
    | '/api/market-news'
    | '/api/dodge/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MbmaRoute: typeof MbmaRoute
  TargetAttackRoute: typeof TargetAttackRoute
  ApiConstructionFeedsRoute: typeof ApiConstructionFeedsRoute
  ApiMarketNewsRoute: typeof ApiMarketNewsRoute
  ApiDodgeProjectsRoute: typeof ApiDodgeProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mbma': {
      id: '/mbma'
      path: '/mbma'
      fullPath: '/mbma'
      preLoaderRoute: typeof MbmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-attack': {
      id: '/target-attack'
      path: '/target-attack'
      fullPath: '/target-attack'
      preLoaderRoute: typeof TargetAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/construction-feeds': {
      id: '/api/construction-feeds'
      path: '/api/construction-feeds'
      fullPath: '/api/construction-feeds'
      preLoaderRoute: typeof ApiConstructionFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-news': {
      id: '/api/market-news'
      path: '/api/market-news'
      fullPath: '/api/market-news'
      preLoaderRoute: typeof ApiMarketNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dodge/projects': {
      id: '/api/dodge/projects'
      path: '/api/dodge/projects'
      fullPath: '/api/dodge/projects'
      preLoaderRoute: typeof ApiDodgeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MbmaRoute: MbmaRoute,
  TargetAttackRoute: TargetAttackRoute,
  ApiConstructionFeedsRoute: ApiConstructionFeedsRoute,
  ApiMarketNewsRoute: ApiMarketNewsRoute,
  ApiDodgeProjectsRoute: ApiDodgeProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
